### ISSUE TITLE
adabins models cannot be loaded

### ISSUE THREAD

**Issue by MRCVEngineer** [zhyever/Monocular-Depth-Estimation-Toolbox#13]
Hi, appreciate your great work. I just downloaded adabins models adabins_efnetb5_kitti and ran this command:
python tools/test.py configs/adabins/adabins_efnetb5ap_kitti_24e.py     checkpoints/adabins_efnetb5_kitti.pth     --show-dir results_vis

however I got an error:
2022-04-22 12:42:15,566 - depth - INFO - Loaded 652 images. Totally 45 invalid pairs are filtered
Using cache found in /home/endeavor_cv/.cache/torch/hub/rwightman_gen-efficientnet-pytorch_master
Use load_from_local loader
Traceback (most recent call last):
  File "tools/test.py", line 196, in <module>
    main()
  File "tools/test.py", line 133, in main
    checkpoint = load_checkpoint(model, args.checkpoint, map_location='cpu')
  File "/home/endeavor_cv/anaconda3/envs/depthtool/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 513, in load_checkpoint
    checkpoint = _load_checkpoint(filename, map_location, logger)
  File "/home/endeavor_cv/anaconda3/envs/depthtool/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 451, in _load_checkpoint
    return CheckpointLoader.load_checkpoint(filename, map_location, logger)
  File "/home/endeavor_cv/anaconda3/envs/depthtool/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 244, in load_checkpoint
    return checkpoint_loader(filename, map_location)
  File "/home/endeavor_cv/anaconda3/envs/depthtool/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 261, in load_from_local
    checkpoint = torch.load(filename, map_location=map_location)
  File "/home/endeavor_cv/anaconda3/envs/depthtool/lib/python3.7/site-packages/torch/serialization.py", line 592, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/endeavor_cv/anaconda3/envs/depthtool/lib/python3.7/site-packages/torch/serialization.py", line 851, in _load
    result = unpickler.load()
  File "/home/endeavor_cv/anaconda3/envs/depthtool/lib/python3.7/site-packages/torch/serialization.py", line 843, in persistent_load
    load_tensor(data_type, size, key, _maybe_decode_ascii(location))
  File "/home/endeavor_cv/anaconda3/envs/depthtool/lib/python3.7/site-packages/torch/serialization.py", line 831, in load_tensor
    storage = zip_file.get_storage_from_record(name, size, dtype).storage()
RuntimeError: [enforce fail at inline_container.cc:222] . file not found: archive/data/93867484692576

It seems like function load_checkpoint cannot load this model, maybe the file you uploaded is corrupt? I tried using depthformer models and they worked perfectly fine.

Thanks

**Comment by zhyever** [comment]
Thanks for your attention. I have uploaded a new version. You can try again. :D

**Comment by zhyever** [comment]
Close for now. If there are other broken models, please contact me and I will fix the problems.
