### ISSUE TITLE
Training with pertained model

### ISSUE THREAD

**Issue by HIROYUKISHIONO** [zhyever/Monocular-Depth-Estimation-Toolbox#21]
Hi, I had a problem with using a depthformer model trained on my dataset for further training.
Within the config, I set the path to the model located within my previous work_dirs, but training code printed this message.
I appreciate if you tell us how we can enable training with our own pretrained mode.
Thanks!

/content/drive/MyDrive/Monocular-Depth-Estimation-Toolbox/depth/models/backbones/depthformer_swin.py:663: UserWarning: DeprecationWarning: pretrained is a deprecated, please use "init_cfg" instead
  warnings.warn('DeprecationWarning: pretrained is a deprecated, '
2022-05-16 05:52:40,851 - depth - INFO - Use load_from_local loader
Traceback (most recent call last):
  File "tools/train.py", line 168, in <module>
    main()
  File "tools/train.py", line 135, in main
    model.init_weights()
  File "/usr/local/lib/python3.7/site-packages/mmcv/runner/base_module.py", line 117, in init_weights
    m.init_weights()
  File "/content/drive/MyDrive/Monocular-Depth-Estimation-Toolbox/depth/models/backbones/depthformer_swin.py", line 842, in init_weights
    table_current = self.state_dict()[table_key]
KeyError: 'backbone.stages.0.blocks.0.attn.w_msa.relative_position_bias_table'
Killing subprocess 9723
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/usr/local/lib/python3.7/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/usr/local/lib/python3.7/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/local/bin/python', '-u', 'tools/train.py', '--local_rank=0', 'configs/depthformer/depthformer_swint_w7_nyu.py', '--launcher', 'pytorch']' returned non-zero exit status 1.

**Comment by zhyever** [comment]
From your reported information, I guess you change the `pretrained` ([this line of codes](https://github.com/zhyever/Monocular-Depth-Estimation-Toolbox/blob/2c054b40461b64c60ff7d1a4d7f4f0833e716eb7/configs/depthformer/depthformer_swinl_22k_w7_nyu.py#L7)) to your own model path. However, that is only for the encoder.

If you wanna fine-tune a pre-trained model, you can set a `load_from` in the config. The corresponding config file can be like this:
```
... raw configs ...

### add this line to your config.
load_from = 'path/to/your/model.pth'
```

**Comment by zhyever** [comment]
Close for now.
