### ISSUE TITLE
visualize_point-cloud problem

### ISSUE THREAD

**Issue by guijuzhejiang** [zhyever/Monocular-Depth-Estimation-Toolbox#24]
hi, i to ran this command in blob/main/docs/inference.md: 

python ./tools/misc/visualize_point-cloud.py \
    configs/depthformer/depthformer_swinl_22k_w7_nyu.py \
    checkpoints/depthformer_swinl_22k_w7_nyu.pth \
    --output-dir point-cloud

result:
Traceback (most recent call last):
  File "./tools/misc/visualize_point-cloud.py", line 187, in <module>
    main()
  File "./tools/misc/visualize_point-cloud.py", line 108, in main
    cfg = build_data_cfg(cfg, args.cfg_options)
  File "./tools/misc/visualize_point-cloud.py", line 63, in build_data_cfg
    show_pipeline = cfg.eval_pipeline
  File "/home/ray/.conda/envs/sfm_py38/lib/python3.8/site-packages/mmcv/utils/config.py", line 506, in __getattr__
    return getattr(self._cfg_dict, name)
  File "/home/ray/.conda/envs/sfm_py38/lib/python3.8/site-packages/mmcv/utils/config.py", line 48, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'eval_pipeline'

**Comment by zhyever** [comment]
I forget to include the `eval_pipeline` in the configs. I will complete it soon.
